// <auto-generated />
using BankCalendar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankCalendar.Migrations
{
    [DbContext(typeof(BankCalendarContext))]
    partial class BankCalendarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BankCalendar.Models.CalendarItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<string>("Day");

                    b.Property<string>("Ends");

                    b.Property<string>("Event");

                    b.Property<string>("Location");

                    b.Property<string>("Starts");

                    b.HasKey("ID");

                    b.ToTable("CalendarItem");
                });
#pragma warning restore 612, 618
        }
    }
}
